name: BeyondBorderUnlocked
version: 1.0.0
main: com.maximde.beyondBorderUnlocked.BeyondBorderUnlocked
api-version: 1.18
depends: packetevents
commands:
  beyondborder:
    description: Manage border settings
